image: debian:jessie

stages:
  - build
  - report

before_script:
  - apt-get -q update >/dev/null 2>&1 && apt-get -y install curl >/dev/null 2>&1
  - ./github-status.sh pending

job-build-sucess:
  stage: build
  script:
    - /bin/true

job-build-fail:
  stage: build
  script:
    - /bin/false

job-report-failure:
  stage: report
  when: on_failure
  script:
    - ./github-status.sh failure

job-report-success:
  stage: report
  when: on_success
  script:
    - ./github-status.sh success
