image: debian:jessie

stages:
  - build
  - report

before_script:
  - apt-get -q update >/dev/null 2>&1 && apt-get -y install curl >/dev/null 2>&1
  - ./github-status.sh pending
  - /bin/false

job-build:
  stage: build
  script:
    - /bin/true

job-report-failure:
  stage: report
  when: on_failure
  script:
    - ./github-status.sh failure

job-report-success:
  stage: report
  when: on_success
  script:
    - ./github-status.sh success
